sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk11
addons:
    apt:
      update: true
    chrome: stable
bbefore_install:
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - export CHROME_BIN=/usr/bin/google-chrome
install: true
jobs:
  include:
    - script: mvn clean install -Dsuite=Regression -Ddriver.type=CHROME -Dog.url=$OGAME_URL -Dog.user=$OGAME_USER -Dog.pass=$OGAME_PASS
      name: "Chrome"
