version: 2.0

jobs:
  "ogame":
    docker:
      - image: markhobson/maven-chrome:jdk-11
    working_directory: ~/ogame
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: OGAME
          command: mvn clean install -Dsuite=Regression -Ddriver.type=CHROME -Dog.url=https://s166-pl.ogame.gameforge.com/ -Dog.user=triko2020@gmail.com -Dog.pass=qweasdzxc
      - run:
          name: Slavik
          command: mvn clean install -Dsuite=slavik -Ddriver.type=CHROME -Dog.url=https://s166-pl.ogame.gameforge.com/ -Dog.user=slav4uk2011@gmail.com -Dog.pass=slavik1988

workflows:
  version: 2
  commit:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - "ogame"